title: Using starter project animations
hero_image: images/banner.png
description: Using starter project animations
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Using starter project animations
