---
title: Utiliser les animations du projet de démarrage
hero_image: images/banner.png
description: Utilise les animations du projet de démarrage.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Utiliser les animations du projet de démarrage
