title: Use starter project animations
hero_image: images/banner.png
description: Use starter project animations.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Use starter project animations
